### ISSUE TITLE
May be missing some important codes

### ISSUE THREAD

**Issue by Nusselder9** [Jackn0/snn_optimal_conversion_pipeline#1]
Hi, thanks for your cool work.

But there may be missing some important codes, e.g. args parser. 

And what args should be when runing the main file.

**Comment by Jackn0** [comment]
Args parser is in models/setting.py. 
First changing the .pth file name at the line:16 in the main_simulation.py file (model_save_name)
The common is like: python main_simulation.py --arch VGG16 --dataset CIFAR10 --batch_size 128 --thresh 1 --step 1 --T 32
